---
title: "ds2_final_report"
author: "Weijia Xiong, Yimeng Shang, Xue Jin"
date: "5/15/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Describe your data set. Provide proper motivation for your work.

What questions are you trying to answer?
How did you prepare and clean the data?
 

# Exploratory analysis/visualization

Is there any interesting structure present in the data?
What were your findings?
Here you can use any techniques as long as they are adequately explained. If you cannot find anything interesting, then describe what you tried and show that there isn’t much visible structure. Data science is NOT manipulating the data in some way until you get an answer.

 

# Models

What predictor variables did you include?
What technique did you use? What assumptions, if any, are being made by using this technique?
If there were tuning parameters, how did you pick their values?
Discuss the training/test performance if you have a test data set.
Which variables play important roles in predicting the response?
Explain/visualize the final model you select.
What are the limitations of the models you used (if there are any)? Are the models flexible enough to capture the underlying truth?


# Conclusions

What were your findings? Are they what you expect? What insights into the data can you make?
